### ISSUE TITLE
Things Checklist

### ISSUE THREAD

**Issue by ragamouf** [au-research/ARDC-23-things#11]
This is a checklist of things to do for each thing

## Checklist

- [ ]  Check [GDrive](https://drive.google.com/drive/folders/1-4rs7sub4llJYYqeQniEbB5Iiui44QDf) for updated content
- [ ]  Fix problematic content
- [ ] Check the thing against the [Style Guide](https://github.com/au-research/ARDC-23-things/wiki/Style-Guide)
~~- [ ]  Copy to "things" directory~~ *all done*
~~- [ ]  Clean up formatting~~ *all done*
~~- [ ]  Replaced outdated standard text (sharing)~~ *all done*
~~- [ ]  Remove outdated standard text (credly)~~ *all done*

~~## Join us and tweet refrain~~ *removed from things*

**Comment by tom-h** [comment]
@mpfl perhaps update this in light of your discussion with Tash? :-)

**Comment by mpfl** [comment]
> @mpfl perhaps update this in light of your discussion with Tash? :-)

Good call.

**Comment by tom-h** [comment]
~~See PR https://github.com/au-research/ARDC-23-things/pull/47 for an alternate way of adding in the Join us and tweet refrain.~~

~~See PR #48 for alternate way, using layouts~~

Now that PR #48 is merged, this makes including the sharing/credly stuff redundant.

**Comment by tom-h** [comment]
Here is a link to the GDrive folder with the edited things to check:

https://drive.google.com/drive/folders/1-4rs7sub4llJYYqeQniEbB5Iiui44QDf

**Comment by tom-h** [comment]
PR #65 renames things 1-9. Make sure that you sync your fork if you are working on these. Let me know if you have a hard time resolving this. Details on how to sync your fork are in the wiki.
